### ISSUE TITLE
Support for Design Jobs without the atomic transaction

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot-app-design-builder#111]
### Environment
* Nautobot version:  2.0.0
* nautobot-design-builder version:  any

`Only applies to v2`

Atomic transactions come at a considerable cost when the number of objects are measured in the thousands, this was why atomic transactions were removed in nautobot v2 as they are way to problematic compared to the value they add for most use cases. Design Builder has a valid use case but the total time to generate ~5k objects on generic compute can take 18 hours to run the job and on CPU optimized compute can take over 6 hours for the same job. When comparing the same job to using the API the job is substantially slower than using a separate script with the API.

### Proposed Functionality

V2 only job class that removes the atomic transaction

**Comment by abates** [comment]
@whitej6 Do you have a full example I can use for benchmarking?

**Comment by whitej6** [comment]
@abates I will mention you in the thread in slack with the details
