### ISSUE TITLE
Design Jobs no longer load in 2.2.3 from Git Repo

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-design-builder#145]
### Environment
* Python version:  3.11
* Nautobot version:  2.2.3
* nautobot-design-builder version:  2.0.0

### Expected Behavior
Job properly loads in adn registers via git repo.

### Observed Behavior
Works fine in versions up to 2.2.2, once Nautobot core is upgraded to 2.2.3 which I know has some changes back to a more 1.x celery task construct the jobs no longer register.

### Steps to Reproduce
1. Setup gitrepo with designs
2. sync the gitrepo
3. See error about `did you call register_job` eventhough it works in 2.2.1.

**Comment by abates** [comment]
I don't think this is an issue with design builder itself, but with a change in Nautobot 2.2.3. The [documentation](https://docs.nautobot.com/projects/core/en/stable/development/jobs/#installing-jobs) actually says that jobs repos must have a top-level `__init__.py` file, but previous versions of Nautobot didn't seem to enforce this.

Try adding a top-level `__init__.py` and see if the jobs load then.

**Comment by jeffkala** [comment]
Adding the top-level `__init__.py` did indeed fix this.
