### ISSUE TITLE
!next-prefix action tag using location and prefix type fails with prefix_length is null

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-design-builder#154]
### Environment
* Python version:  3.8
* Nautobot version:  2.2.3
* nautobot-design-builder version:  2.0.0

### Expected Behavior
!next-prefix action tag will get-next properly when a filter criteria is specified to determine the "parent" prefixes to search in.

### Observed Behavior

```
Prefix None failed validation

prefix_length: This field cannot be null.
```

### Steps to Reproduce
1. Create design
```yaml
---
prefixes:
  - "!next_prefix":
      locations: "{{ site_name.parent.parent.parent.id }}"
      type: "container"
      length: "{{ ipam_templates[site_size | lower]['template_prefix_size'] | int }}"
    status__name: "Active"
    description: "{{ site_name }} Parent Prefix"
    type: "container"
    "!ref": "parent_prefix"
```
2.  Have available prefixes in the parent location
3. Execute the job.
4. Gives error
```python
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_design_builder/design_job.py", line 143, in run
    return self._run_in_transaction(dryrun, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_design_builder/design_job.py", line 209, in _run_in_transaction
    raise ex
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_design_builder/design_job.py", line 190, in _run_in_transaction
    self.implement_design(context, design_file, not dryrun)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_design_builder/design_job.py", line 138, in implement_design
    self.environment.implement_design(design, commit)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_design_builder/design.py", line 761, in implement_design
    raise ex
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_design_builder/design.py", line 746, in implement_design
    self._create_objects(self.model_map[key], value)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_design_builder/design.py", line 822, in _create_objects
    model.save()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_design_builder/design.py", line 613, in save
    raise errors.DesignValidationError(self) from validation_error
nautobot_design_builder.errors.DesignValidationError: <unprintable DesignValidationError object>
```

For additonal testing did validate the same _get_next functionality from ORM returns a value.
```
>>> stuff = {"locations": l.parent.parent.parent.id, "type": "container"}
>>> query = Q(**stuff)
>>> query
<Q: (AND: ('locations', UUID('7e3cff0a-629a-42fe-b578-d02ab4cff4ae')), ('type', 'container'))>
>>> prefixes = Prefix.objects.filter(query)
>>> prefixes
<PrefixQuerySet [<Prefix: 10.34.0.0/16>, <Prefix: 1.34.0.0/16>, <Prefix: 1.41.0.0/16>]>
>>> length = 25
>>> _get_next(prefixes, length)
'10.34.0.0/25'
```

**Comment by abates** [comment]
I think the issue here is that the `length` field is being passed in as a string, but it needs to be an integer. Try this:

```yaml
---
prefixes:
  - "!next_prefix":
      locations: "{{ site_name.parent.parent.parent.id }}"
      type: "container"
      length: {{ ipam_templates[site_size | lower]['template_prefix_size'] | int }}
    status__name: "Active"
    description: "{{ site_name }} Parent Prefix"
    type: "container"
    "!ref": "parent_prefix"
```

**Comment by jeffkala** [comment]
Did try this and still got the same error.  Even just hardcoded the length and it fails.

```python
---
prefixes:
  - "!next_prefix":
      locations: "{{ site_name.parent.parent.parent.id }}"
      type: "container"
      length: 25
    status__name: "Active"
    description: "{{ site_name }} Parent Prefix"
    type: "container"
    "!ref": "parent_prefix"
```

**Comment by jeffkala** [comment]
Does seem like its something about no prefixes available in certain circumstances.  If I play around with it and make the length much smaller it results in the expected error around "no prefixes available for ..."  still debugging further to see what is happening but if I ensure the prefix is available it works as expected.

**Comment by jeffkala** [comment]
Still troubleshooting, but the culprit was a relationship with the attributes below. Once the relationship was deleted and nautobot restarted, the design job started working.
![image](https://github.com/nautobot/nautobot-app-design-builder/assets/48843785/bbdae9be-6d35-4fe4-ade6-830d0df9fdff)

**Comment by itdependsnetworks** [comment]
In a similar example, I just changed the source and destination to not have potential namepsace issues with the method names, such as prefix -> prefix1 and VLAN -> VLAN1 and that fixed the issue.

**Comment by abates** [comment]
@jeffkala do you consider this a bug that we should try and mitigate?

**Comment by jeffkala** [comment]
At least maybe we can just document it and provide best practices to work around it?  I'm not fully onboard that we "must" mitigate it as it seems rare its hit.

**Comment by abates** [comment]
PR #200 introduces an error message and protection from overwriting built-in fields. This image is an example error message in the job result:
![Screenshot 2024-10-24 at 10 24 25 AM](https://github.com/user-attachments/assets/9af76371-7db2-4f74-8f89-40db0d157b18)

**Comment by jeffkala** [comment]
> PR #200 introduces an error message and protection from overwriting built-in fields. This image is an example error message in the job result: ![Screenshot 2024-10-24 at 10 24 25 AM](https://private-user-images.githubusercontent.com/358901/379816466-9af76371-7db2-4f74-8f89-40db0d157b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODY1NTMsIm5iZiI6MTcyOTc4NjI1MywicGF0aCI6Ii8zNTg5MDEvMzc5ODE2NDY2LTlhZjc2MzcxLTdkYjItNGY3NC04Zjg5LTQwZGIwZDE1N2IxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNjEwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzFmZDcwZDMwODQ3YzI3ODliMWQwNDVlNmU3OTNlMmJmZGRiODgyMWY2YzliNjgyZTIxOGZiOGQxODI1ZTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E4jvSf30KXNTJIyZu6z9P5suYAsq1u8kb2dhVgPlbEM)

looks great @abates
