### ISSUE TITLE
Model attribute namespace collisions

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot-app-design-builder#160]
### Environment
* Python version:  3.9
* Nautobot version:  1.6
* nautobot-design-builder version:  1.2.0

### Expected Behavior
Design builder should be entirely agnostic to any naming of custom relationships, custom fields, or other built in properties/attributes/field names, etc that exist on models.

### Observed Behavior
Certain named attributes throughout design-builder have effectively been implemented as reserved attributes/names and cause errors when referenced.

### Steps to Reproduce
1. Create a custom model named Environment
2. Create a custom relationship between Device and Environment
3. Create a design that attempts to create a device (even without populating the custom relationship)
4. Run the design
5. Receive an error that 'Device' does not have an attribute named 'environmnet'.

**Comment by abates** [comment]
Okay, I've refactored design builder and limited the number of attributes that are in the `ModelInstance` class. This is where the majority of the problems are. The remaining items are:
- `design_instance` this is a terrible name, but it is the actual underlying database model instance that is being proxied by the `ModelInstance`
- `design_metadata` this is relevant information that associates design changes, and the current implementation, with the proxied model.
- `_design_instance_parent` the parent object, this is necessary for foreign-key and reverse foreign-key associations in design builder. It is also used when an error occurs to assist in notifying the user where in the design the error occurred.
- `relationship_manager` a database manager that represents how to find the current object

Also are the following methods:
`connect`
`send`
`_update_fields`
`save`

I think the chances of collision are significantly lowered with these changes. With the `develop` branch and Nautobot 2 I should be able to leverage logging to provides warnings if any collisions do actually occur.

**Comment by abates** [comment]
Fixed in ltm-1.6
