### ISSUE TITLE
Design deployment is `Active` even if the Design Job failed

### ISSUE THREAD

**Issue by gertzakis** [nautobot/nautobot-app-design-builder#170]
### Environment
* Python version: 3.11 
* Nautobot version: 1.6.23 
* nautobot-design-builder version: 1.3.0

### Expected Behavior
When I run a Design Job and it fails, I expected the Design Deployment status to be something similar. 

### Observed Behavior
The Design Deployment status shown as `Active`. 

### Steps to Reproduce
1. Run a Design Job that it fails
2. Go to Design Deployments and check that deployment
3.

**Comment by chadell** [comment]
fixed in #172
