### ISSUE TITLE
Design Composition

### ISSUE THREAD

**Issue by nkallergis** [nautobot/nautobot-app-design-builder#54]
### Environment
* Nautobot version:  2.x
* design-builder version:  next

### Proposed Functionality
Building on issue #52.

At some point, when there will be many services defined, it could be necessary to establish a hierarchical design relationship, so a high-level design could be composed of lower-level ones. So, one design job could call several minor design jobs under one umbrella. Moreover, there could be a need to establish dependencies between the services, so one technical service could not be implemented until its dependencies are in place. For instance, a l3vpn requires the network management service in a device.

**Comment by abates** [comment]
@chadell @nkallergis 

Where do we stand on this? Do we consider this already delivered with the data protection built in at this point, or it there a different intent? As far as a parent design calling smaller designs I think that is already available by using multiple design templates, but not sure if that completely covers the desired feature.

**Comment by nkallergis** [comment]
I'm perfectly OK with closing this one but maybe @chadell has a different view?

**Comment by chadell** [comment]
The way that we support design composition is by referencing objects/attributes owned by other design and enforcing protection. For now, I think that we don't need any higher abstraction.
